### ISSUE TITLE
Use of old method names

### ISSUE THREAD

**Issue by PabloCastellano** [alvations/spaghetti-tagger#1]
Method _batch_tag()_ doesn't exist anymore.

```
(nltk)$ python demo.py 
*** First-time use of cess tagger ***
Training tagger ...
Tagger trained with cess usingUnigramTagger and BigramTagger.
Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    print spa.pos_tag(test_sent)
  File "/home/pablo/src/NLTK/spaghetti-tagger/spaghetti.py", line 63, in pos_tag
    tagger = cesstag(mmwe)
  File "/home/pablo/src/NLTK/spaghetti-tagger/spaghetti.py", line 51, in __init__
    tagged_cess_nomwe = batch_pos_tag(cess_nomwe)
  File "/home/pablo/src/NLTK/spaghetti-tagger/spaghetti.py", line 68, in batch_pos_tag
    return tagger.uni.batch_tag(sentences)
AttributeError: 'UnigramTagger' object has no attribute 'batch_tag'
```

**Comment by alvations** [comment]
Thanks @PabloCastellano for reporting the error! I've updated the code to suit the latest version of NLTK =)
