### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by ghost** [alvations/spaghetti-tagger#2]
Hi,

I'm testing the spaghetti-tagger for the first time and I ran into a problem, any idea how to make it work? I'd really appreciate it! :

Running from MacOS Sierra, version 10.12.6
The nltk version is 3.2.4.

```
/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5 /Users/missogra/PycharmProjects/try/spagetthi_test.py
Traceback (most recent call last):
  File "/Users/missogra/PycharmProjects/try/spagetthi_test.py", line 9, in <module>
    print (sgt.pos_tag(test_sents))
  File "/Users/missogra/PycharmProjects/try/spaghetti.py", line 70, in pos_tag
    return tagger.uni.tag(tokens)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk/tag/sequential.py", line 63, in tag
    tags.append(self.tag_one(tokens, i, tags))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk/tag/sequential.py", line 83, in tag_one
    tag = tagger.choose_tag(tokens, index, history)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk/tag/sequential.py", line 142, in choose_tag
    return self._context_to_tag.get(context)
TypeError: unhashable type: 'list'
```

**Comment by alvations** [comment]
I suspect you didn't pass in the right object type for to the tagger function.

Could you post the code that you have in `spagetthi_test.py`?

**Comment by ghost** [comment]
You're absolutely right! My bad! Thanks for the quick response :)
